### ISSUE TITLE
SMASPREAD in INDICATORS?

### ISSUE THREAD

**Issue by montychase** [stevenshizzleh/the-north-star#12]
In the notes you:

'Added SMASPREAD to be used by DCA buy strategy.'

But I don't see it in there. Was that purposefully dropped?

**Comment by Fransenson** [comment]
It is in there. Just checked.

**Comment by montychase** [comment]
I was picking up the files from the critical release tag  https://github.com/stevenshizzleh/the-north-star/releases/tag/1.0.2  (perhaps an old one)

You're right, the project assets INDICATORS.properties does include them

**Comment by Fransenson** [comment]
Ah @stevenshizzle might have missed putting the correct file.

**Comment by jldathome** [comment]
@stevenshizzle - Is it possible to confirm that the right files/ settings are there when you are able please (I'm in the future Oz!)....your notes state you lowered RSI...but not to what....the file I have states 80 and I'm just mildly concerned that i might be running your previous settings. Cheers & love your work..

**Comment by jldathome** [comment]
I've just seen that the Source Code file contains the updated files..all good

**Comment by GvY85** [comment]
So in the release the zipfile is correct but the seperate .properties files not?

In the same release the contents of the zip differs from the seperate files

**Comment by stevenshizzleh** [comment]
I'm as puzzled as you are as to why the files did not match the zip and what's on the repository front page. Download the zip and you'll be good to go.
