### ISSUE TITLE
LowBB

### ISSUE THREAD

**Issue by XcidTrader** [stevenshizzleh/the-north-star#16]
DEFAULT_D_buy_strategy = LOWBB
DEFAULT_D_buy_value = 107.5

Im curious as to your thinking around your LowBB value?

A great Lowbb buy value is >5, combined with other indicators is a real safe buy.

**Comment by pyto00** [comment]
With lowbb set so huge, you have more buy opportunities on a uptrend then lowbb set <10. 
This has to be accompagnied by other buy strategies to work. 

Thats why I think he set it so high.
But I also want to hear his version on it.

**Comment by stevenshizzleh** [comment]
@XcidTrader we do not use the strategy you quoted. This is our setting for DEFAULT_D in the settings.analyzer.json file: 
>		  "DEFAULT_D_buy_strategy": "HIGHBB",
>		  "DEFAULT_D_buy_value": 56.00,
>		  "DEFAULT_D_buy_value_limit": 2.00,
The HIGHBB is set, along with other indicators and buy strategies, to frame a situation in an uptrend and buy on signals of sustained strength.

Feel free to adjust as you see fit and to try out new things! Experimenting and understanding the settings is part of the adventure 👍
