### ISSUE TITLE
there is no settings.analyzer.json

### ISSUE THREAD

**Issue by juato4** [stevenshizzleh/the-north-star#6]

**Comment by Fransenson** [comment]
From the FAQ:

Q: Will you be releasing PTMagic settings?

A: At the moment our intent is to continue to improve this specific setting. We feel if we can do this one thing extremely well, then it's going to represent a large majority of the overall solution. Eventually, we would like to get extremely good at trading other trends. So the vision is that one day we'll have The North Star as a Single Market Setting in PTMagic, alongside other refined settings.

**Comment by juato4** [comment]
sad

**Comment by stevenshizzleh** [comment]
@juato4 -- I'd recommend you give them a shot. These settings perform better than anything we've ever done with PTMagic before. Your choice my friend.
