### ISSUE TITLE
error notice in binance

### ISSUE THREAD

**Issue by angelsomar** [stevenshizzleh/the-north-star#7]
![image](https://user-images.githubusercontent.com/36096512/39409350-236e48a4-4bab-11e8-9773-deb731c17cdf.png)
Hello
thanks for the effort
error notice in binance

**Comment by Fransenson** [comment]
You have to have the indicators.properies applied also.

**Comment by Hattingg** [comment]
indicators.properties:

# ####################################
# ####### PTMagic Current Setting ########
# PTMagic_ActiveSetting = ToTheMoon
# PTMagic_LastChanged = 29/04/2018 14:30
# ####################################
# ####################################
# ####### PTMagic Current Setting ########
# PTMagic_ActiveSetting = ToTheMoon
# PTMagic_LastChanged = 29/04/2018 14:30
# ####################################
#########################################################################
##
#The Wolfs Of Crypto #
#PT2 Strategy Analyser V2 - no.1 Setting tool for Profit Trailer 2!#
##
##
#Find all the information about this awesome tool: #
##
##
#WolfsWiki:https://github.com/smoochy/WolfsOfCrypto/wiki#
##
##
#Full Version:https://www.tradingview.com/script/aKS0Z4xk-#
##
##
#Telegram Channel:https://t.me/theWolfs_ofCrypto#
##
##
#Free Trial Version:https://www.tradingview.com/script/HKOauWFk#
##
##
#Youtube Video: https://www.youtube.com/watch?v=t8om31ntt8g#
##
##
#Buy ProfitTrailer: https://profittrailer.com/pt/TheWolfsOfCrypto/#
##
#########################################################################
BB_std = 2
BB_candle_period = 900
BB_length = 20
SMA_cross_candles = 2
SMA_candle_period = 900
SMA_fast_length = 2
SMA_slow_length = 5
EMA_cross_candles = 3
EMA_candle_period = 900
EMA_fast_length = 8
EMA_slow_length = 13
RSI_candle_period = 900
RSI_length = 14
STOCH_length = 14
MACD_candle_period = 900
MACD_fast_length = 3
MACD_slow_length = 5
MACD_signal = 5
SOM_trigger_length = 288
# PTMagic_SingleMarketSettings - Written on 29/04/2018 14:50:19
# ########################################################################

**Comment by Porkepie** [comment]
Same issue here I believe one of the values isn't supported in binance.

**Comment by Frailian** [comment]
Same problem here. Can't figure out what values aren't supported. 300, 900, and 3600 are all supported according to the exchanges page on the ProfitTrailer wiki https://wiki.profittrailer.com/doku.php?id=exchanges

**Comment by stevenshizzleh** [comment]
I run Binance and haven't had any problems with this yet folks. I'll keep this open for a little while in case the community comes up with a solution, but we've been testing all kinds of candles w/ Bianace for about 2 1/2 weeks without these errors.

**Comment by montychase** [comment]
I am using BINANCE and I'm not experiencing the error (PM2 on CentOS 7)

**Comment by angelsomar** [comment]
Apparently user problem

I tried a clean Binance installation and everything works without error

**Comment by stevenshizzleh** [comment]
We're thinking the issue is that we use 5 buy strategies. If your DEFAULT_min_buy_volum is too low, then you'll have a lot of pairs in your possible buy log. In this case, there are 5x as many calls to the Binance API as before and the API gets a bit choked up.

Set your DEFAULT_min_buy_volume to minimum 3000 for ETH and 780 for BTC.

**Comment by angelsomar** [comment]
I was investigating a bit, apparently the problem is STOCH but in the version pt2

all of us who no longer have problems are in version 2.0.1

please validate

**Comment by Frailian** [comment]
I'm on version 2.0.1 and get the error. As mentioned above, I only see it on PTnotifications and only on startup. Doesn't seem to be affecting the bot otherwise.
